### ISSUE TITLE
Prints out “... 10 more ...” for complex objects

### ISSUE THREAD

**Issue by fasiha** [Schniz/infer-types#1]
I’ll add an example in a few hours but for a deeply nested object, this will produce the same abbreviated type signature as VS Code shows when hovering over the exported variable.

Is there any way to override the depth?

**Comment by fasiha** [comment]
You can fix it by adding a third parameter to `checker.typeToString`, specifically, `ts.TypeFormatFlags.NoTruncation`. I’ll send a pull request later tonight.

**Comment by fasiha** [comment]
Sorry, took a couple of nights more than I expected but #2 is the merge request as promised.

**Comment by Schniz** [comment]
Released in `0.0.2` (commit f84e8005ad78c7982b16467e9b7117cf6b8285e8)
